// Authors : Laurent Barraud, Bastian Chollet, Luca Coduri,
// Guillaume Duvoisin, Guilain Mbayo & David Rossy
// SI-CA2a - november 2019 - updated in 2026 - CPNV school

var acartesData = [
   { "id": 0,  "titre": "Question", "texte": "Question",      "couleur": "blue",  "type": "question", "prix": 0 },
   { "id": 1,  "titre": "Français", "texte": "Rédaction",     "couleur": "black", "type": "normal",   "prix": 1000 },
   { "id": 2,  "titre": "Français", "texte": "Littérature",   "couleur": "black", "type": "normal",   "prix": 1000 },
   { "id": 3,  "titre": "Chance",   "texte": "Chance",        "couleur": "white", "type": "chance",   "prix": 0 },
   { "id": 4,  "titre": "Méca",     "texte": "Matériaux",     "couleur": "black", "type": "normal",   "prix": 1000 },
   { "id": 5,  "titre": "Méca",     "texte": "Usinage",       "couleur": "black", "type": "normal",   "prix": 1000 },
   { "id": 6,  "titre": "Question", "texte": "Question",      "couleur": "blue",  "type": "question", "prix": 0 },
   { "id": 7,  "titre": "Langues",  "texte": "Allemand",      "couleur": "black", "type": "normal",   "prix": 1000 },
   { "id": 8,  "titre": "Langues",  "texte": "Anglais",       "couleur": "black", "type": "normal",   "prix": 1000 },
   { "id": 9,  "titre": "Chance",   "texte": "Chance",        "couleur": "white", "type": "chance",   "prix": 0 },
   { "id": 10, "titre": "Média",    "texte": "Multimédia",    "couleur": "black", "type": "normal",   "prix": 1000 },
   { "id": 11, "titre": "Média",    "texte": "Web",           "couleur": "black", "type": "normal",   "prix": 1000 },
   { "id": 12, "titre": "Question", "texte": "Question",      "couleur": "blue",  "type": "question", "prix": 0 },
   { "id": 13, "titre": "ECG",      "texte": "Economie",      "couleur": "black", "type": "normal",   "prix": 1000 },
   { "id": 14, "titre": "ECG",      "texte": "Droit",         "couleur": "black", "type": "normal",   "prix": 1000 },
   { "id": 15, "titre": "Chance",   "texte": "Chance",        "couleur": "white", "type": "chance",   "prix": 0 },
   { "id": 16, "titre": "Sport",    "texte": "Football",      "couleur": "black", "type": "normal",   "prix": 1000 },
   { "id": 17, "titre": "Sport",    "texte": "Basketball",    "couleur": "black", "type": "normal",   "prix": 1000 },
   { "id": 18, "titre": "Question", "texte": "Question",      "couleur": "blue",  "type": "question", "prix": 0 },
   { "id": 19, "titre": "Maths",    "texte": "Géométrie",     "couleur": "black", "type": "normal",   "prix": 1000 },
   { "id": 20, "titre": "Maths",    "texte": "Algèbre",       "couleur": "black", "type": "normal",   "prix": 1000 },
   { "id": 21, "titre": "Chance",   "texte": "Chance",        "couleur": "white", "type": "chance",   "prix": 0 },
   { "id": 22, "titre": "Info",     "texte": "Système",       "couleur": "black", "type": "normal",   "prix": 1000 },
   { "id": 23, "titre": "Info",     "texte": "Développement", "couleur": "black", "type": "normal",   "prix": 1000 },
   { "id": 24, "titre": "CFC",      "texte": "CFC",           "couleur": "cyan",  "type": "cfc",      "prix": 0 },
   { "id": 25, "titre": "Info",     "texte": "Bases de données", "couleur": "black", "type": "normal",   "prix": 1000 },
   { "id": 26, "titre": "Info",     "texte": "Réseaux",          "couleur": "black", "type": "normal",   "prix": 1000 },
   { "id": 27, "titre": "Question", "texte": "Question",         "couleur": "blue",  "type": "question", "prix": 0 },
   { "id": 28, "titre": "Culture",  "texte": "Histoire",         "couleur": "black", "type": "normal",   "prix": 1000 },
   { "id": 29, "titre": "Culture",  "texte": "Géographie",       "couleur": "black", "type": "normal",   "prix": 1000 },
   { "id": 30, "titre": "Chance",   "texte": "Chance",           "couleur": "white", "type": "chance",   "prix": 0 },
   { "id": 31, "titre": "Science",  "texte": "Physique",         "couleur": "black", "type": "normal",   "prix": 1000 },
   { "id": 32, "titre": "Science",  "texte": "Chimie",           "couleur": "black", "type": "normal",   "prix": 1000 },
   { "id": 33, "titre": "Question", "texte": "Question",         "couleur": "blue",  "type": "question", "prix": 0 },
   { "id": 34, "titre": "Art",      "texte": "Musique",          "couleur": "black", "type": "normal",   "prix": 1000 },
   { "id": 35, "titre": "Art",      "texte": "Dessin",           "couleur": "black", "type": "normal",   "prix": 1000 },
   { "id": 36, "titre": "Chance",   "texte": "Chance",           "couleur": "white", "type": "chance",   "prix": 0 },
   { "id": 37, "titre": "Projet",   "texte": "Travail de groupe","couleur": "black", "type": "normal",   "prix": 1000 },
   { "id": 38, "titre": "Projet",   "texte": "Présentation",     "couleur": "black", "type": "normal",   "prix": 1000 },
   { "id": 39, "titre": "Départ",   "texte": "Départ",           "couleur": "cyan",  "type": "normal",   "prix": 0 }
];
